version: '3.8'

services:
  ecommerce:
    build: 
      context: ./services/ecommerce
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - store
      - exchange
      - fidelity
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=mydatabase
      - SERVICE_NAME=ecommerce-service

  store:
    build:
      context: ./services/store
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=mydatabase
      - SERVICE_NAME=store-service

  exchange:
    build:
      context: ./services/exchange
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    deploy:
      replicas: 3
    networks:
      - app-network
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=mydatabase
      - SERVICE_NAME=exchange-service

  fidelity:
    build:
      context: ./services/fidelity
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - app-network
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=mydatabase
      - SERVICE_NAME=fidelity-service

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
