spring:
  application:
    name: ecommerce
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:mydatabase}

server:
  port: 8080

store:
  url: http://store:8081
exchange:
  url: http://exchange:8082
fidelity:
  url: http://fidelity:8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      storeProduct:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
      exchangeRate:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
      storeSale:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  timelimiter:
    instances:
      default:
        timeoutDuration: 1s
      storeProduct:
        timeoutDuration: 1s
      exchangeRate:
        timeoutDuration: 1s
      storeSale:
        timeoutDuration: 1s

# Logs detalhados para Resilience4j e RestTemplate
logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    com.faulttolerance.ecommerce.service.PurchaseService: DEBUG
