spring:
  application:
    name: ecommerce-service
  config:
    import: optional:file:../application.yml

server:
  port: 8080

store:
  url: http://store:8081
exchange:
  url: http://exchange:8082
fidelity:
  url: http://fidelity:8083
