groups:
  - name: service_alerts
    rules:
      - alert: HighLatency
        expr: rate(purchase_request_seconds_sum[5m]) / rate(purchase_request_seconds_count[5m]) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High latency in purchase requests
          description: Purchase request latency is above 2 seconds for 5 minutes

      - alert: CircuitBreakerOpen
        expr: resilience4j_circuitbreaker_state{state="OPEN"} > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Circuit Breaker is OPEN
          description: Circuit breaker {{ $labels.name }} is in OPEN state

      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[5m]) / rate(http_server_requests_seconds_count[5m]) * 100 > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: Error rate is above 5% for 5 minutes

      - alert: LowInventory
        expr: store_product_inventory < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Low product inventory
          description: Product {{ $labels.product }} has less than 10 items in stock

      - alert: BonusProcessingDelay
        expr: fidelity_pending_bonus_points > 100
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Bonus points processing delay
          description: More than 100 bonus points pending processing for 10 minutes

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Service is down
          description: Service {{ $labels.job }} is down
