global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'ecommerce'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ecommerce:8080']
        labels:
          application: 'ecommerce-service'

  - job_name: 'store'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['store:8081']
        labels:
          application: 'store-service'

  - job_name: 'exchange'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['exchange:8082']
        labels:
          application: 'exchange-service'

  - job_name: 'fidelity'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['fidelity:8083']
        labels:
          application: 'fidelity-service'
