spring:
  application:
    name: exchange-service
  config:
    import: optional:file:../application.yml

server:
  port: 8082

# Configurações específicas para simular falhas
resilience4j.circuitbreaker:
  instances:
    exchange:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2

# Cache configuration
spring.cache:
  redis:
    time-to-live: 600000 # 10 minutes
    cache-null-values: true
